# Generated by Django 4.0.3 on 2022-05-13 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='chauffeurs',
            fields=[
                ('id_chauffeur', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='utilisateurs',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('entreprise', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='vehicules',
            fields=[
                ('id_vehicule', models.AutoField(primary_key=True, serialize=False)),
                ('matricule', models.CharField(max_length=50)),
                ('classe', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='positions',
            fields=[
                ('id_position', models.AutoField(primary_key=True, serialize=False)),
                ('latitude', models.CharField(max_length=50)),
                ('longitude', models.CharField(max_length=50)),
                ('date_heure', models.DateTimeField()),
                ('id_chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BE.chauffeurs')),
                ('id_vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BE.vehicules')),
            ],
        ),
    ]
